"""Make columns nullable and add unique constraint

Revision ID: 1bba57a81eea
Revises: 0481276c6c83
Create Date: 2024-12-17 23:16:51.909305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bba57a81eea'
down_revision: Union[str, None] = '0481276c6c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingest_user_project_csv', 'email',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ingest_user_project_csv', 'buid',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ingest_user_project_csv', 'github_username',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.create_index('ix_ingest_user_project_csv_unique', 'ingest_user_project_csv', [sa.text("COALESCE(project_name, '')"), sa.text("COALESCE(project_tag, '')"), sa.text("COALESCE(first_name, '')"), sa.text("COALESCE(last_name, '')"), sa.text("COALESCE(email, '')"), sa.text("COALESCE(buid, '')"), sa.text("COALESCE(github_username, '')")], unique=True)
    op.create_unique_constraint('uq_ingest_user_project_csv_all_columns', 'ingest_user_project_csv', ['project_name', 'project_tag', 'first_name', 'last_name', 'email', 'buid', 'github_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ingest_user_project_csv_all_columns', 'ingest_user_project_csv', type_='unique')
    op.drop_index('ix_ingest_user_project_csv_unique', table_name='ingest_user_project_csv')
    op.alter_column('ingest_user_project_csv', 'github_username',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ingest_user_project_csv', 'buid',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ingest_user_project_csv', 'email',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
