"""Change null constraints on IngestuserProjectCSV

Revision ID: 94fce2a59224
Revises: b0a85b0a1488
Create Date: 2024-12-17 21:05:47.505382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94fce2a59224'
down_revision: Union[str, None] = 'b0a85b0a1488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingest_user_project_csv', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ingest_user_project_csv', 'buid',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ingest_user_project_csv', 'github_username',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingest_user_project_csv', 'github_username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ingest_user_project_csv', 'buid',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ingest_user_project_csv', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
